### ISSUE TITLE
cant install new software

### ISSUE THREAD

**Issue by nerkn** [awilby/slam-docker#1]
I wanted to install nano to edit files but I got those errors, why signature is broken?

**root@robo25:/ORB_SLAM2/Examples/ROS/ORB_SLAM2# apt install nano**
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package nano
**root@robo25:/ORB_SLAM2/Examples/ROS/ORB_SLAM2# apt update**
Get:2 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Get:3 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]
0% [2 InRelease gpgv 109 kB] [Waiting for headers] [3 InRelease 33.2 kB/109 kB 30%] [Waiting for headers]Couldn't create tempfiles for splitting up /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_xeniErr:2 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
  Could not execute 'apt-key' to verify signature (is gnupg installed?)
Get:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
0% [4 InRelease gpgv 107 kB] [Waiting for headers] [3 InRelease 33.2 kB/109 kB 30%] [Waiting for headers]Couldn't create tempfiles for splitting up /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_xeniErr:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
  Could not execute 'apt-key' to verify signature (is gnupg installed?)
Get:1 http://archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
Get:5 http://packages.ros.org/ros/ubuntu xenial InRelease [4678 B]
0% [5 InRelease gpgv 4678 B] [1 InRelease 225 kB/247 kB 91%] [3 InRelease 86.0 kB/109 kB 79%]Couldn't create tempfiles for splitting up /var/lib/apt/lists/partial/packages.ros.org_ros_ubuntu_dists_xenial_InReleaErr:5 http://packages.ros.org/ros/ubuntu xenial InRelease
  Could not execute 'apt-key' to verify signature (is gnupg installed?)
Err:1 http://archive.ubuntu.com/ubuntu xenial InRelease     Couldn't create tempfiles for splitting up /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_xenial_InRelease
  Could not execute 'apt-key' to verify signature (is gnupg installed?)
Err:3 http://security.ubuntu.com/ubuntu xenial-security InReleaseng up /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_xenial-security_InRelease
  Could not execute 'apt-key' to verify signature (is gnupg installed?)
Reading package lists... Done
W: GPG error: http://archive.ubuntu.com/ubuntu xenial-updates InRelease: Could not execute 'apt-key' to verify signature (is gnupg installed?)
E: The repository 'http://archive.ubuntu.com/ubuntu xenial-updates InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://archive.ubuntu.com/ubuntu xenial-backports InRelease: Could not execute 'apt-key' to verify signature (is gnupg installed?)
E: The repository 'http://archive.ubuntu.com/ubuntu xenial-backports InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://packages.ros.org/ros/ubuntu xenial InRelease: Could not execute 'apt-key' to verify signature (is gnupg installed?)
E: The repository 'http://packages.ros.org/ros/ubuntu xenial InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://archive.ubuntu.com/ubuntu xenial InRelease: Could not execute 'apt-key' to verify signature (is gnupg installed?)
E: The repository 'http://archive.ubuntu.com/ubuntu xenial InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by awilby** [comment]
I can't replicate this error on my system and I don't know what version of Docker you're using, but the image builds with vim so there is already a text editor available.
